### ISSUE TITLE
Exception "Impossible de récupérer un identifiant."

### ISSUE THREAD

**Issue by tuxayo** [papjul/ade-planning-viewer#13]
J'ai cette erreur, comment investiguer la cause?
Par exemple savoir si ça viens bien de mon serveur ou si c'est sur l'ADE?

**Comment by papjul** [comment]
Ça n’a jamais marché ou c’est nouveau ? parce que je viens de tester à l’instant chez moi, c’est OK.

L’erreur signifie que dans le retour de la page de l’ADE (où se trouve l’identifiant), l’identifiant ne s’y trouve pas. Si tu n’as pas touché le fichier reset.yaml, trois possibilités :
1. Le serveur de l’ADE était down à ce moment (je pense que tu aurais dû avoir un timeout plutôt)
2. L’IP de ton serveur a été bannie
3. La configuration par défaut de cURL/PHP a été bidouillée (si c’était la 1re fois que tu testais, ou que la config a été modifiée depuis la dernière fois où ça marchait)
4. Ton serveur ou/et PHP n’est pas configuré pour pouvoir atteindre des sites à l’extérieur (si c’était la 1re fois que tu testais, ou que la config a été modifiée depuis la dernière fois où ça marchait)

**Comment by tuxayo** [comment]
Il me semble que c'est le premier reset depuis une migration de Lighttpd vers Nginx.

2: Ça marchait avant.

3/4: comment je peux check ça?

**Comment by papjul** [comment]
Déjà en passant de Lighttpd à Nginx, tu es passé à PHP-FPM (sauf erreur de ma part) donc le php.ini n’est pas le même. Tu n’as plus qu’à faire un diff, y a un paramètre pour ça.

**Comment by tuxayo** [comment]
J'ai reboot nginx et php-fm et ça marche...
