### ISSUE TITLE
Q : Possibilité d'utiliser du json à la place du yaml ?

### ISSUE THREAD

**Issue by KenAlin** [papjul/ade-planning-viewer#14]
Bonjour,
Je suis étudiant à l'école Polytech Montpellier, qui utilise également ADE pour gérer les emplois du temps. J'ai créé [un petit site](http://wave-it.fr/polytech/agenda) qui télécharge les fichiers ical de certaines *ressources* à intervalle régulier depuis le site de l'école (merci les tâches CRON :p), et affiche les plannings des sections à ma sauce (compatible mobile, détection des examens, etc).
Je souhaite aussi afficher les images des plannings, mais pour cela, il me faut ce fameux *identifier* renouvelé environ une fois par jour.

J'ai trouvé votre projet sur Github, et je voudrais savoir si il m'était possible de reprendre votre script `reset.php`, pour aller chercher un identifiant ? Avec crédits, bien entendu.

Aussi, j'ai une petite contrainte ... mon site est sur un hébergement mutualisé (budget :/), et PECL Yaml ne peut donc pas y être installé. Je ne connais pas du tout cette extension, mais d'après vous, serait-il possible que je réadapte votre code pour utiliser du json à la place, ou PECL Yaml est trop ancré dans le projet pour envisager la moindre adaptation ?

**Comment by papjul** [comment]
Tu peux utiliser ce script sans problèmes en le redistribuant sous les termes de la même licence (AGPLv3+). Concernant YAML, l’issue #11 devrait résoudre ton soucis, je vais essayer d’y jeter un œil cet après-midi (personne n’en avait exprimé le besoin particulier jusqu’à présent). Si tu ne peux pas utiliser Composer, tu devras télécharger manuellement les fichiers dans un dossier vendor/ ou appeler Composer sur ta machine en local, puis transférer les fichiers sur l’hébergement.

**Comment by papjul** [comment]
Ça devrait être bon maintenant. Si PECL Yaml n’est pas installé, l’appli bascule automatiquement sur Symfony YAML (doit être installé par Composer). Dis-moi si cela te convient, ou si le JSON est vraiment vital pour toi…

**Comment by KenAlin** [comment]
Merci beaucoup ! Je vais tester ça (et faire mes premiers pas sur Symphony, au passage). :)
