### ISSUE TITLE
Où se trouve le fichier vendor/autoload.php ?

### ISSUE THREAD

**Issue by GeeksdelaCave** [papjul/ade-planning-viewer#15]
"Bien que l’application soit conçue pour fonctionner sans dépendances externes, [...]"
Bonjour,
Je souhaiterai remettre en route le Planning d'Informaix, pour l'IUT Informatique AMU d'Aix-en-Provence, qui ne fonctionne plus suite à une mise à jour d'ADE. Suite à un téléchargement du code via l'archive, et après upload sur un serveur perso, j'obtiens deux erreurs (enfin, surtout une grosse) :

`
Warning: require_once(/home/tandt/www/planning/vendor/autoload.php): failed to open stream: No such file or directory in /home/tandt/www/planning/src/Planning.class.php on line 64

Fatal error: require_once(): Failed opening required '/home/tandt/www/planning/vendor/autoload.php' (include_path='.:/usr/local/share/php:/usr/lib/php5/pear') in /home/tandt/www/planning/src/Planning.class.php on line 64
`

Ainsi, j'aimerai savoir où donc trouver ce fichier ?
Merci à vous.

**Comment by papjul** [comment]
Il est créé par Composer. PECL Yaml n'est pas installé sur le serveur sur lequel tu exécutes le planning, donc il y a une dépendance sur Symfony YAML installé par Composer. Si tu as plus de questions, je te contacterais via l'asso.

**Comment by papjul** [comment]
Tout ceci est précisé dans la partie Prérequis.
