### ISSUE TITLE
 Version ade et jsp inaccessible

### ISSUE THREAD

**Issue by PanRem** [papjul/ade-planning-viewer#19]
Bonjour,

Je cherche à utiliser cet outil afin de faciliter la visualisation des emplois du temps dans mon établissement. Le souci étant que nous n'avons accès ni à la version http://monurl/jsp (redirection en boucle sans fin), ni à la version http://monurl/ade (aucune permission d'accès).

L'outil est il adaptable pour un usage sur l'url direct?
Si non, pensez vous que développer un équivalent dans ce but soit réalisable?

**Comment by papjul** [comment]
Bonjour, ça fait quelques années que je n'ai pas vérifié si l'outil fonctionnait toujours.

Il est possible qu'ADE ait évolué de sorte que ça ne fonctionne plus.

Mais je peux essayer de regarder. Quelle est l'URL de base ?

**Comment by PanRem** [comment]
De visu pourtant ça ressemble plus a une ancienne version (6.5.4)
Mon principal souci pour scrap les données est le besoin d’interaction (aucune data ne s'affiche sans cliquer sur les elements) ce qui va rendre la récupération particulièrement longue je pense.

https://planif.esiee.fr/direct/
id : lecteur1
mdp : Ø

**Comment by papjul** [comment]
L'URL https://planif.esiee.fr/jsp/ fonctionne chez moi, avec les identifiants donnés.
J'ai pu générer une image sans problèmes

**Comment by PanRem** [comment]
effectivement il semblerait que c'était un souci originaire de mon navigateur. Merci

**Comment by papjul** [comment]
Je viens de faire un correctif sur le script reset qui empêchait la réinitialisation de l'identifiant.
Sinon, cela semble fonctionner correctement sur la base du planning 2024-2025 de mon ancienne université, avec par moments quelques images qui ne chargent pas quand on enchaîne un peu trop les requêtes, mais ça c'est un soucis de longue date (#16) ;)
